export const CUSTOMER_ACTIVITY_PAGE_VIEW_STORAGE_PREFIX = "customer-activity:page-view:"

export const CUSTOMER_ACTIVITY_CART_ABANDONED_STORAGE_KEY = "customer-activity:cart-abandoned-sent"

export const CUSTOMER_AUDIT_TIMELINE_LIMIT = 50

export const CUSTOMER_ACTIVITY_PRODUCT_TITLE_MAX_LENGTH = 512
export const CUSTOMER_ACTIVITY_VARIANT_ID_MAX_LENGTH = 64
export const CUSTOMER_ACTIVITY_VARIANT_TITLE_MAX_LENGTH = 256
export const CUSTOMER_ACTIVITY_PAGE_PATH_MAX_LENGTH = 2048
