export const STOREFRONT_SEARCH_MIN_LENGTH = 2;
export const STOREFRONT_SEARCH_DEBOUNCE_MS = 300;
export const STOREFRONT_SEARCH_LIMIT_PER_GROUP = 6;
export const STOREFRONT_SEARCH_QUERY_STALE_MS = 60_000;
export const STOREFRONT_SEARCH_TRENDING_LIMIT = 5;
export const STOREFRONT_SEARCH_TRENDING_SOURCE_COUNT = 2;
export const STOREFRONT_SEARCH_LOCALE_MIN_LENGTH = 1;
