import type { QueryKey } from "@tanstack/react-query";

import { CONSTANTS } from "~/src/constants";

export const REALTIME_INVALIDATION_HUB = {
  ADMIN: "admin",
  STOREFRONT: "storefront"
} as const;

export type RealtimeInvalidationHubName = (typeof REALTIME_INVALIDATION_HUB)[keyof typeof REALTIME_INVALIDATION_HUB];

/** Query-key prefixes every admin shell tab subscribes to. */
export const ADMIN_REALTIME_QUERY_PREFIXES = [
  CONSTANTS.QUERY_KEYS.AUDIT_LOG.ADMIN.PAGE,
  CONSTANTS.QUERY_KEYS.AUDIT_LOG.ADMIN.STATS,
  CONSTANTS.QUERY_KEYS.ORDER.ADMIN.ORDERS,
  CONSTANTS.QUERY_KEYS.USER.ADMIN.CUSTOMERS,
  CONSTANTS.QUERY_KEYS.CATEGORY.ADMIN.ALL,
  CONSTANTS.QUERY_KEYS.CATEGORY.ADMIN.STATS,
  CONSTANTS.QUERY_KEYS.COLLECTION.ADMIN.ALL,
  CONSTANTS.QUERY_KEYS.COLLECTION.ADMIN.STATS,
  CONSTANTS.QUERY_KEYS.PRODUCT.ADMIN.ALL,
  CONSTANTS.QUERY_KEYS.PRODUCT.ADMIN.STATS,
  CONSTANTS.QUERY_KEYS.PRODUCT_ATTRIBUTE.ADMIN.ALL,
  CONSTANTS.QUERY_KEYS.PRODUCT_ATTRIBUTE.ADMIN.STATS
] as const satisfies readonly QueryKey[];

/** Query-key prefixes every storefront tab subscribes to. */
export const STOREFRONT_REALTIME_QUERY_PREFIXES = [
  CONSTANTS.QUERY_KEYS.PRODUCT.ALL,
  CONSTANTS.QUERY_KEYS.PRODUCT.BY_HANDLE,
  CONSTANTS.QUERY_KEYS.PRODUCT.RELATED_BY_CATEGORY,
  CONSTANTS.QUERY_KEYS.CART.AVAILABILITY,
  CONSTANTS.QUERY_KEYS.CATEGORY.ALL,
  CONSTANTS.QUERY_KEYS.CATEGORY.BY_HANDLE,
  CONSTANTS.QUERY_KEYS.COLLECTION.ALL,
  CONSTANTS.QUERY_KEYS.COLLECTION.BY_HANDLE
] as const satisfies readonly QueryKey[];
