/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125FaqRouteImport } from './routes/{-$locale}.faq'
import { Route as Char123LocaleChar125ExchangesAndReturnsRouteImport } from './routes/{-$locale}.exchanges-and-returns'
import { Route as Char123LocaleChar125CartRouteImport } from './routes/{-$locale}.cart'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}.auth'
import { Route as Char123LocaleChar125AccountRouteImport } from './routes/{-$locale}.account'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}.about'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}.products.index'
import { Route as Char123LocaleChar125CollectionsIndexRouteImport } from './routes/{-$locale}.collections.index'
import { Route as Char123LocaleChar125CategoriesIndexRouteImport } from './routes/{-$locale}.categories.index'
import { Route as Char123LocaleChar125ProductsHandleRouteImport } from './routes/{-$locale}.products.$handle'
import { Route as Char123LocaleChar125CollectionsHandleRouteImport } from './routes/{-$locale}.collections.$handle'
import { Route as Char123LocaleChar125CategoriesHandleRouteImport } from './routes/{-$locale}.categories.$handle'
import { Route as Char123LocaleChar125AuthSignUpRouteImport } from './routes/{-$locale}.auth.sign-up'
import { Route as Char123LocaleChar125AuthSignInRouteImport } from './routes/{-$locale}.auth.sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125FaqRoute = Char123LocaleChar125FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125ExchangesAndReturnsRoute =
  Char123LocaleChar125ExchangesAndReturnsRouteImport.update({
    id: '/exchanges-and-returns',
    path: '/exchanges-and-returns',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CartRoute =
  Char123LocaleChar125CartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AccountRoute =
  Char123LocaleChar125AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CollectionsIndexRoute =
  Char123LocaleChar125CollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CategoriesIndexRoute =
  Char123LocaleChar125CategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProductsHandleRoute =
  Char123LocaleChar125ProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CollectionsHandleRoute =
  Char123LocaleChar125CollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CategoriesHandleRoute =
  Char123LocaleChar125CategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthSignUpRoute =
  Char123LocaleChar125AuthSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthSignInRoute =
  Char123LocaleChar125AuthSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/cart': typeof Char123LocaleChar125CartRoute
  '/{-$locale}/exchanges-and-returns': typeof Char123LocaleChar125ExchangesAndReturnsRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/categories/$handle': typeof Char123LocaleChar125CategoriesHandleRoute
  '/{-$locale}/collections/$handle': typeof Char123LocaleChar125CollectionsHandleRoute
  '/{-$locale}/products/$handle': typeof Char123LocaleChar125ProductsHandleRoute
  '/{-$locale}/categories/': typeof Char123LocaleChar125CategoriesIndexRoute
  '/{-$locale}/collections/': typeof Char123LocaleChar125CollectionsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/cart': typeof Char123LocaleChar125CartRoute
  '/{-$locale}/exchanges-and-returns': typeof Char123LocaleChar125ExchangesAndReturnsRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/categories/$handle': typeof Char123LocaleChar125CategoriesHandleRoute
  '/{-$locale}/collections/$handle': typeof Char123LocaleChar125CollectionsHandleRoute
  '/{-$locale}/products/$handle': typeof Char123LocaleChar125ProductsHandleRoute
  '/{-$locale}/categories': typeof Char123LocaleChar125CategoriesIndexRoute
  '/{-$locale}/collections': typeof Char123LocaleChar125CollectionsIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/cart': typeof Char123LocaleChar125CartRoute
  '/{-$locale}/exchanges-and-returns': typeof Char123LocaleChar125ExchangesAndReturnsRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/categories/$handle': typeof Char123LocaleChar125CategoriesHandleRoute
  '/{-$locale}/collections/$handle': typeof Char123LocaleChar125CollectionsHandleRoute
  '/{-$locale}/products/$handle': typeof Char123LocaleChar125ProductsHandleRoute
  '/{-$locale}/categories/': typeof Char123LocaleChar125CategoriesIndexRoute
  '/{-$locale}/collections/': typeof Char123LocaleChar125CollectionsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/auth'
    | '/{-$locale}/cart'
    | '/{-$locale}/exchanges-and-returns'
    | '/{-$locale}/faq'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/categories/$handle'
    | '/{-$locale}/collections/$handle'
    | '/{-$locale}/products/$handle'
    | '/{-$locale}/categories/'
    | '/{-$locale}/collections/'
    | '/{-$locale}/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/auth'
    | '/{-$locale}/cart'
    | '/{-$locale}/exchanges-and-returns'
    | '/{-$locale}/faq'
    | '/{-$locale}'
    | '/api/auth/$'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/categories/$handle'
    | '/{-$locale}/collections/$handle'
    | '/{-$locale}/products/$handle'
    | '/{-$locale}/categories'
    | '/{-$locale}/collections'
    | '/{-$locale}/products'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/auth'
    | '/{-$locale}/cart'
    | '/{-$locale}/exchanges-and-returns'
    | '/{-$locale}/faq'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/categories/$handle'
    | '/{-$locale}/collections/$handle'
    | '/{-$locale}/products/$handle'
    | '/{-$locale}/categories/'
    | '/{-$locale}/collections/'
    | '/{-$locale}/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/faq': {
      id: '/{-$locale}/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof Char123LocaleChar125FaqRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/exchanges-and-returns': {
      id: '/{-$locale}/exchanges-and-returns'
      path: '/exchanges-and-returns'
      fullPath: '/{-$locale}/exchanges-and-returns'
      preLoaderRoute: typeof Char123LocaleChar125ExchangesAndReturnsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cart': {
      id: '/{-$locale}/cart'
      path: '/cart'
      fullPath: '/{-$locale}/cart'
      preLoaderRoute: typeof Char123LocaleChar125CartRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/account': {
      id: '/{-$locale}/account'
      path: '/account'
      fullPath: '/{-$locale}/account'
      preLoaderRoute: typeof Char123LocaleChar125AccountRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/collections/': {
      id: '/{-$locale}/collections/'
      path: '/collections'
      fullPath: '/{-$locale}/collections/'
      preLoaderRoute: typeof Char123LocaleChar125CollectionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/categories/': {
      id: '/{-$locale}/categories/'
      path: '/categories'
      fullPath: '/{-$locale}/categories/'
      preLoaderRoute: typeof Char123LocaleChar125CategoriesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/products/$handle': {
      id: '/{-$locale}/products/$handle'
      path: '/products/$handle'
      fullPath: '/{-$locale}/products/$handle'
      preLoaderRoute: typeof Char123LocaleChar125ProductsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/collections/$handle': {
      id: '/{-$locale}/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/{-$locale}/collections/$handle'
      preLoaderRoute: typeof Char123LocaleChar125CollectionsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/categories/$handle': {
      id: '/{-$locale}/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/{-$locale}/categories/$handle'
      preLoaderRoute: typeof Char123LocaleChar125CategoriesHandleRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth/sign-up': {
      id: '/{-$locale}/auth/sign-up'
      path: '/sign-up'
      fullPath: '/{-$locale}/auth/sign-up'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignUpRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/sign-in': {
      id: '/{-$locale}/auth/sign-in'
      path: '/sign-in'
      fullPath: '/{-$locale}/auth/sign-in'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignInRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125AuthRouteChildren {
  Char123LocaleChar125AuthSignInRoute: typeof Char123LocaleChar125AuthSignInRoute
  Char123LocaleChar125AuthSignUpRoute: typeof Char123LocaleChar125AuthSignUpRoute
}

const Char123LocaleChar125AuthRouteChildren: Char123LocaleChar125AuthRouteChildren =
  {
    Char123LocaleChar125AuthSignInRoute: Char123LocaleChar125AuthSignInRoute,
    Char123LocaleChar125AuthSignUpRoute: Char123LocaleChar125AuthSignUpRoute,
  }

const Char123LocaleChar125AuthRouteWithChildren =
  Char123LocaleChar125AuthRoute._addFileChildren(
    Char123LocaleChar125AuthRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AccountRoute: typeof Char123LocaleChar125AccountRoute
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRouteWithChildren
  Char123LocaleChar125CartRoute: typeof Char123LocaleChar125CartRoute
  Char123LocaleChar125ExchangesAndReturnsRoute: typeof Char123LocaleChar125ExchangesAndReturnsRoute
  Char123LocaleChar125FaqRoute: typeof Char123LocaleChar125FaqRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125CategoriesHandleRoute: typeof Char123LocaleChar125CategoriesHandleRoute
  Char123LocaleChar125CollectionsHandleRoute: typeof Char123LocaleChar125CollectionsHandleRoute
  Char123LocaleChar125ProductsHandleRoute: typeof Char123LocaleChar125ProductsHandleRoute
  Char123LocaleChar125CategoriesIndexRoute: typeof Char123LocaleChar125CategoriesIndexRoute
  Char123LocaleChar125CollectionsIndexRoute: typeof Char123LocaleChar125CollectionsIndexRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125AccountRoute: Char123LocaleChar125AccountRoute,
  Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRouteWithChildren,
  Char123LocaleChar125CartRoute: Char123LocaleChar125CartRoute,
  Char123LocaleChar125ExchangesAndReturnsRoute:
    Char123LocaleChar125ExchangesAndReturnsRoute,
  Char123LocaleChar125FaqRoute: Char123LocaleChar125FaqRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125CategoriesHandleRoute:
    Char123LocaleChar125CategoriesHandleRoute,
  Char123LocaleChar125CollectionsHandleRoute:
    Char123LocaleChar125CollectionsHandleRoute,
  Char123LocaleChar125ProductsHandleRoute:
    Char123LocaleChar125ProductsHandleRoute,
  Char123LocaleChar125CategoriesIndexRoute:
    Char123LocaleChar125CategoriesIndexRoute,
  Char123LocaleChar125CollectionsIndexRoute:
    Char123LocaleChar125CollectionsIndexRoute,
  Char123LocaleChar125ProductsIndexRoute:
    Char123LocaleChar125ProductsIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
