/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125CheckoutRouteImport } from './routes/{-$locale}.checkout'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}.auth'
import { Route as Char123LocaleChar125AdminRouteImport } from './routes/{-$locale}.admin'
import { Route as Char123LocaleChar125AccountRouteImport } from './routes/{-$locale}.account'
import { Route as Char123LocaleChar125StorefrontRouteImport } from './routes/{-$locale}._storefront'
import { Route as DevEmailsRouteImport } from './routes/dev.emails'
import { Route as Char123LocaleChar125CheckoutIndexRouteImport } from './routes/{-$locale}.checkout.index'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}.admin.index'
import { Route as Char123LocaleChar125AccountIndexRouteImport } from './routes/{-$locale}.account.index'
import { Route as Char123LocaleChar125StorefrontIndexRouteImport } from './routes/{-$locale}._storefront.index'
import { Route as Char123LocaleChar125DevDatagridRouteImport } from './routes/{-$locale}.dev.datagrid'
import { Route as Char123LocaleChar125AuthSignUpRouteImport } from './routes/{-$locale}.auth.sign-up'
import { Route as Char123LocaleChar125AuthSignInRouteImport } from './routes/{-$locale}.auth.sign-in'
import { Route as Char123LocaleChar125AuthResetPasswordRouteImport } from './routes/{-$locale}.auth.reset-password'
import { Route as Char123LocaleChar125AuthForgotPasswordRouteImport } from './routes/{-$locale}.auth.forgot-password'
import { Route as Char123LocaleChar125AdminSettingsRouteImport } from './routes/{-$locale}.admin.settings'
import { Route as Char123LocaleChar125AdminOverviewRouteImport } from './routes/{-$locale}.admin.overview'
import { Route as Char123LocaleChar125AdminMarketingRouteImport } from './routes/{-$locale}.admin.marketing'
import { Route as Char123LocaleChar125AdminCouponsRouteImport } from './routes/{-$locale}.admin.coupons'
import { Route as Char123LocaleChar125AdminContentRouteImport } from './routes/{-$locale}.admin.content'
import { Route as Char123LocaleChar125AdminCatalogRouteImport } from './routes/{-$locale}.admin.catalog'
import { Route as Char123LocaleChar125AdminAuditRouteImport } from './routes/{-$locale}.admin.audit'
import { Route as Char123LocaleChar125AccountWishlistRouteImport } from './routes/{-$locale}.account.wishlist'
import { Route as Char123LocaleChar125AccountSessionsRouteImport } from './routes/{-$locale}.account.sessions'
import { Route as Char123LocaleChar125AccountProfileRouteImport } from './routes/{-$locale}.account.profile'
import { Route as Char123LocaleChar125AccountPaymentRouteImport } from './routes/{-$locale}.account.payment'
import { Route as Char123LocaleChar125AccountOverviewRouteImport } from './routes/{-$locale}.account.overview'
import { Route as Char123LocaleChar125AccountAddressesRouteImport } from './routes/{-$locale}.account.addresses'
import { Route as Char123LocaleChar125StorefrontTermsOfServiceRouteImport } from './routes/{-$locale}._storefront.terms-of-service'
import { Route as Char123LocaleChar125StorefrontPrivacyPolicyRouteImport } from './routes/{-$locale}._storefront.privacy-policy'
import { Route as Char123LocaleChar125StorefrontFaqRouteImport } from './routes/{-$locale}._storefront.faq'
import { Route as Char123LocaleChar125StorefrontExchangesAndReturnsRouteImport } from './routes/{-$locale}._storefront.exchanges-and-returns'
import { Route as Char123LocaleChar125StorefrontCartRouteImport } from './routes/{-$locale}._storefront.cart'
import { Route as Char123LocaleChar125StorefrontAboutRouteImport } from './routes/{-$locale}._storefront.about'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as Char123LocaleChar125AdminOrdersIndexRouteImport } from './routes/{-$locale}.admin.orders.index'
import { Route as Char123LocaleChar125AdminCustomersIndexRouteImport } from './routes/{-$locale}.admin.customers.index'
import { Route as Char123LocaleChar125AdminCatalogIndexRouteImport } from './routes/{-$locale}.admin.catalog.index'
import { Route as Char123LocaleChar125AccountOrdersIndexRouteImport } from './routes/{-$locale}.account.orders.index'
import { Route as Char123LocaleChar125StorefrontProductsIndexRouteImport } from './routes/{-$locale}._storefront.products.index'
import { Route as Char123LocaleChar125StorefrontCollectionsIndexRouteImport } from './routes/{-$locale}._storefront.collections.index'
import { Route as Char123LocaleChar125StorefrontCategoriesIndexRouteImport } from './routes/{-$locale}._storefront.categories.index'
import { Route as Char123LocaleChar125AdminOrdersOrderIdRouteImport } from './routes/{-$locale}.admin.orders.$orderId'
import { Route as Char123LocaleChar125AdminCustomersIdRouteImport } from './routes/{-$locale}.admin.customers.$id'
import { Route as Char123LocaleChar125AdminCatalogCollectionsRouteImport } from './routes/{-$locale}.admin.catalog.collections'
import { Route as Char123LocaleChar125AccountOrdersIdRouteImport } from './routes/{-$locale}.account.orders.$id'
import { Route as Char123LocaleChar125StorefrontProductsHandleRouteImport } from './routes/{-$locale}._storefront.products.$handle'
import { Route as Char123LocaleChar125StorefrontCollectionsHandleRouteImport } from './routes/{-$locale}._storefront.collections.$handle'
import { Route as Char123LocaleChar125StorefrontCategoriesHandleRouteImport } from './routes/{-$locale}._storefront.categories.$handle'
import { Route as Char123LocaleChar125AdminCatalogProductsIndexRouteImport } from './routes/{-$locale}.admin.catalog.products.index'
import { Route as Char123LocaleChar125AdminCatalogCollectionsIndexRouteImport } from './routes/{-$locale}.admin.catalog.collections.index'
import { Route as Char123LocaleChar125AdminCatalogCategoriesIndexRouteImport } from './routes/{-$locale}.admin.catalog.categories.index'
import { Route as Char123LocaleChar125AdminCatalogProductsHandleRouteImport } from './routes/{-$locale}.admin.catalog.products.$handle'
import { Route as Char123LocaleChar125AdminCatalogCollectionsHandleRouteImport } from './routes/{-$locale}.admin.catalog.collections.$handle'
import { Route as Char123LocaleChar125AdminCatalogCategoriesHandleRouteImport } from './routes/{-$locale}.admin.catalog.categories.$handle'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125CheckoutRoute =
  Char123LocaleChar125CheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminRoute =
  Char123LocaleChar125AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AccountRoute =
  Char123LocaleChar125AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125StorefrontRoute =
  Char123LocaleChar125StorefrontRouteImport.update({
    id: '/_storefront',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const DevEmailsRoute = DevEmailsRouteImport.update({
  id: '/dev/emails',
  path: '/dev/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125CheckoutIndexRoute =
  Char123LocaleChar125CheckoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125CheckoutRoute,
  } as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AccountIndexRoute =
  Char123LocaleChar125AccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125StorefrontIndexRoute =
  Char123LocaleChar125StorefrontIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125DevDatagridRoute =
  Char123LocaleChar125DevDatagridRouteImport.update({
    id: '/dev/datagrid',
    path: '/dev/datagrid',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthSignUpRoute =
  Char123LocaleChar125AuthSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthSignInRoute =
  Char123LocaleChar125AuthSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthResetPasswordRoute =
  Char123LocaleChar125AuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AuthForgotPasswordRoute =
  Char123LocaleChar125AuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const Char123LocaleChar125AdminSettingsRoute =
  Char123LocaleChar125AdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminOverviewRoute =
  Char123LocaleChar125AdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminMarketingRoute =
  Char123LocaleChar125AdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCouponsRoute =
  Char123LocaleChar125AdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminContentRoute =
  Char123LocaleChar125AdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCatalogRoute =
  Char123LocaleChar125AdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminAuditRoute =
  Char123LocaleChar125AdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AccountWishlistRoute =
  Char123LocaleChar125AccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125AccountSessionsRoute =
  Char123LocaleChar125AccountSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125AccountProfileRoute =
  Char123LocaleChar125AccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125AccountPaymentRoute =
  Char123LocaleChar125AccountPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125AccountOverviewRoute =
  Char123LocaleChar125AccountOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125AccountAddressesRoute =
  Char123LocaleChar125AccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125StorefrontTermsOfServiceRoute =
  Char123LocaleChar125StorefrontTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontPrivacyPolicyRoute =
  Char123LocaleChar125StorefrontPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontFaqRoute =
  Char123LocaleChar125StorefrontFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontExchangesAndReturnsRoute =
  Char123LocaleChar125StorefrontExchangesAndReturnsRouteImport.update({
    id: '/exchanges-and-returns',
    path: '/exchanges-and-returns',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontCartRoute =
  Char123LocaleChar125StorefrontCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontAboutRoute =
  Char123LocaleChar125StorefrontAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminOrdersIndexRoute =
  Char123LocaleChar125AdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCustomersIndexRoute =
  Char123LocaleChar125AdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCatalogIndexRoute =
  Char123LocaleChar125AdminCatalogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)
const Char123LocaleChar125AccountOrdersIndexRoute =
  Char123LocaleChar125AccountOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125StorefrontProductsIndexRoute =
  Char123LocaleChar125StorefrontProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontCollectionsIndexRoute =
  Char123LocaleChar125StorefrontCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontCategoriesIndexRoute =
  Char123LocaleChar125StorefrontCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125AdminOrdersOrderIdRoute =
  Char123LocaleChar125AdminOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCustomersIdRoute =
  Char123LocaleChar125AdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCatalogCollectionsRoute =
  Char123LocaleChar125AdminCatalogCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)
const Char123LocaleChar125AccountOrdersIdRoute =
  Char123LocaleChar125AccountOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => Char123LocaleChar125AccountRoute,
  } as any)
const Char123LocaleChar125StorefrontProductsHandleRoute =
  Char123LocaleChar125StorefrontProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontCollectionsHandleRoute =
  Char123LocaleChar125StorefrontCollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125StorefrontCategoriesHandleRoute =
  Char123LocaleChar125StorefrontCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => Char123LocaleChar125StorefrontRoute,
  } as any)
const Char123LocaleChar125AdminCatalogProductsIndexRoute =
  Char123LocaleChar125AdminCatalogProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)
const Char123LocaleChar125AdminCatalogCollectionsIndexRoute =
  Char123LocaleChar125AdminCatalogCollectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminCatalogCollectionsRoute,
  } as any)
const Char123LocaleChar125AdminCatalogCategoriesIndexRoute =
  Char123LocaleChar125AdminCatalogCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)
const Char123LocaleChar125AdminCatalogProductsHandleRoute =
  Char123LocaleChar125AdminCatalogProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)
const Char123LocaleChar125AdminCatalogCollectionsHandleRoute =
  Char123LocaleChar125AdminCatalogCollectionsHandleRouteImport.update({
    id: '/$handle',
    path: '/$handle',
    getParentRoute: () => Char123LocaleChar125AdminCatalogCollectionsRoute,
  } as any)
const Char123LocaleChar125AdminCatalogCategoriesHandleRoute =
  Char123LocaleChar125AdminCatalogCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => Char123LocaleChar125AdminCatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/dev/emails': typeof DevEmailsRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRouteWithChildren
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/checkout': typeof Char123LocaleChar125CheckoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/about': typeof Char123LocaleChar125StorefrontAboutRoute
  '/{-$locale}/cart': typeof Char123LocaleChar125StorefrontCartRoute
  '/{-$locale}/exchanges-and-returns': typeof Char123LocaleChar125StorefrontExchangesAndReturnsRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125StorefrontFaqRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125StorefrontPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125StorefrontTermsOfServiceRoute
  '/{-$locale}/account/addresses': typeof Char123LocaleChar125AccountAddressesRoute
  '/{-$locale}/account/overview': typeof Char123LocaleChar125AccountOverviewRoute
  '/{-$locale}/account/payment': typeof Char123LocaleChar125AccountPaymentRoute
  '/{-$locale}/account/profile': typeof Char123LocaleChar125AccountProfileRoute
  '/{-$locale}/account/sessions': typeof Char123LocaleChar125AccountSessionsRoute
  '/{-$locale}/account/wishlist': typeof Char123LocaleChar125AccountWishlistRoute
  '/{-$locale}/admin/audit': typeof Char123LocaleChar125AdminAuditRoute
  '/{-$locale}/admin/catalog': typeof Char123LocaleChar125AdminCatalogRouteWithChildren
  '/{-$locale}/admin/content': typeof Char123LocaleChar125AdminContentRoute
  '/{-$locale}/admin/coupons': typeof Char123LocaleChar125AdminCouponsRoute
  '/{-$locale}/admin/marketing': typeof Char123LocaleChar125AdminMarketingRoute
  '/{-$locale}/admin/overview': typeof Char123LocaleChar125AdminOverviewRoute
  '/{-$locale}/admin/settings': typeof Char123LocaleChar125AdminSettingsRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/dev/datagrid': typeof Char123LocaleChar125DevDatagridRoute
  '/{-$locale}/': typeof Char123LocaleChar125StorefrontIndexRoute
  '/{-$locale}/account/': typeof Char123LocaleChar125AccountIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/checkout/': typeof Char123LocaleChar125CheckoutIndexRoute
  '/{-$locale}/categories/$handle': typeof Char123LocaleChar125StorefrontCategoriesHandleRoute
  '/{-$locale}/collections/$handle': typeof Char123LocaleChar125StorefrontCollectionsHandleRoute
  '/{-$locale}/products/$handle': typeof Char123LocaleChar125StorefrontProductsHandleRoute
  '/{-$locale}/account/orders/$id': typeof Char123LocaleChar125AccountOrdersIdRoute
  '/{-$locale}/admin/catalog/collections': typeof Char123LocaleChar125AdminCatalogCollectionsRouteWithChildren
  '/{-$locale}/admin/customers/$id': typeof Char123LocaleChar125AdminCustomersIdRoute
  '/{-$locale}/admin/orders/$orderId': typeof Char123LocaleChar125AdminOrdersOrderIdRoute
  '/{-$locale}/categories/': typeof Char123LocaleChar125StorefrontCategoriesIndexRoute
  '/{-$locale}/collections/': typeof Char123LocaleChar125StorefrontCollectionsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125StorefrontProductsIndexRoute
  '/{-$locale}/account/orders/': typeof Char123LocaleChar125AccountOrdersIndexRoute
  '/{-$locale}/admin/catalog/': typeof Char123LocaleChar125AdminCatalogIndexRoute
  '/{-$locale}/admin/customers/': typeof Char123LocaleChar125AdminCustomersIndexRoute
  '/{-$locale}/admin/orders/': typeof Char123LocaleChar125AdminOrdersIndexRoute
  '/{-$locale}/admin/catalog/categories/$handle': typeof Char123LocaleChar125AdminCatalogCategoriesHandleRoute
  '/{-$locale}/admin/catalog/collections/$handle': typeof Char123LocaleChar125AdminCatalogCollectionsHandleRoute
  '/{-$locale}/admin/catalog/products/$handle': typeof Char123LocaleChar125AdminCatalogProductsHandleRoute
  '/{-$locale}/admin/catalog/categories/': typeof Char123LocaleChar125AdminCatalogCategoriesIndexRoute
  '/{-$locale}/admin/catalog/collections/': typeof Char123LocaleChar125AdminCatalogCollectionsIndexRoute
  '/{-$locale}/admin/catalog/products/': typeof Char123LocaleChar125AdminCatalogProductsIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125StorefrontIndexRoute
  '/dev/emails': typeof DevEmailsRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/about': typeof Char123LocaleChar125StorefrontAboutRoute
  '/{-$locale}/cart': typeof Char123LocaleChar125StorefrontCartRoute
  '/{-$locale}/exchanges-and-returns': typeof Char123LocaleChar125StorefrontExchangesAndReturnsRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125StorefrontFaqRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125StorefrontPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125StorefrontTermsOfServiceRoute
  '/{-$locale}/account/addresses': typeof Char123LocaleChar125AccountAddressesRoute
  '/{-$locale}/account/overview': typeof Char123LocaleChar125AccountOverviewRoute
  '/{-$locale}/account/payment': typeof Char123LocaleChar125AccountPaymentRoute
  '/{-$locale}/account/profile': typeof Char123LocaleChar125AccountProfileRoute
  '/{-$locale}/account/sessions': typeof Char123LocaleChar125AccountSessionsRoute
  '/{-$locale}/account/wishlist': typeof Char123LocaleChar125AccountWishlistRoute
  '/{-$locale}/admin/audit': typeof Char123LocaleChar125AdminAuditRoute
  '/{-$locale}/admin/content': typeof Char123LocaleChar125AdminContentRoute
  '/{-$locale}/admin/coupons': typeof Char123LocaleChar125AdminCouponsRoute
  '/{-$locale}/admin/marketing': typeof Char123LocaleChar125AdminMarketingRoute
  '/{-$locale}/admin/overview': typeof Char123LocaleChar125AdminOverviewRoute
  '/{-$locale}/admin/settings': typeof Char123LocaleChar125AdminSettingsRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/dev/datagrid': typeof Char123LocaleChar125DevDatagridRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/checkout': typeof Char123LocaleChar125CheckoutIndexRoute
  '/{-$locale}/categories/$handle': typeof Char123LocaleChar125StorefrontCategoriesHandleRoute
  '/{-$locale}/collections/$handle': typeof Char123LocaleChar125StorefrontCollectionsHandleRoute
  '/{-$locale}/products/$handle': typeof Char123LocaleChar125StorefrontProductsHandleRoute
  '/{-$locale}/account/orders/$id': typeof Char123LocaleChar125AccountOrdersIdRoute
  '/{-$locale}/admin/customers/$id': typeof Char123LocaleChar125AdminCustomersIdRoute
  '/{-$locale}/admin/orders/$orderId': typeof Char123LocaleChar125AdminOrdersOrderIdRoute
  '/{-$locale}/categories': typeof Char123LocaleChar125StorefrontCategoriesIndexRoute
  '/{-$locale}/collections': typeof Char123LocaleChar125StorefrontCollectionsIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125StorefrontProductsIndexRoute
  '/{-$locale}/account/orders': typeof Char123LocaleChar125AccountOrdersIndexRoute
  '/{-$locale}/admin/catalog': typeof Char123LocaleChar125AdminCatalogIndexRoute
  '/{-$locale}/admin/customers': typeof Char123LocaleChar125AdminCustomersIndexRoute
  '/{-$locale}/admin/orders': typeof Char123LocaleChar125AdminOrdersIndexRoute
  '/{-$locale}/admin/catalog/categories/$handle': typeof Char123LocaleChar125AdminCatalogCategoriesHandleRoute
  '/{-$locale}/admin/catalog/collections/$handle': typeof Char123LocaleChar125AdminCatalogCollectionsHandleRoute
  '/{-$locale}/admin/catalog/products/$handle': typeof Char123LocaleChar125AdminCatalogProductsHandleRoute
  '/{-$locale}/admin/catalog/categories': typeof Char123LocaleChar125AdminCatalogCategoriesIndexRoute
  '/{-$locale}/admin/catalog/collections': typeof Char123LocaleChar125AdminCatalogCollectionsIndexRoute
  '/{-$locale}/admin/catalog/products': typeof Char123LocaleChar125AdminCatalogProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/dev/emails': typeof DevEmailsRoute
  '/{-$locale}/_storefront': typeof Char123LocaleChar125StorefrontRouteWithChildren
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRouteWithChildren
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/checkout': typeof Char123LocaleChar125CheckoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/_storefront/about': typeof Char123LocaleChar125StorefrontAboutRoute
  '/{-$locale}/_storefront/cart': typeof Char123LocaleChar125StorefrontCartRoute
  '/{-$locale}/_storefront/exchanges-and-returns': typeof Char123LocaleChar125StorefrontExchangesAndReturnsRoute
  '/{-$locale}/_storefront/faq': typeof Char123LocaleChar125StorefrontFaqRoute
  '/{-$locale}/_storefront/privacy-policy': typeof Char123LocaleChar125StorefrontPrivacyPolicyRoute
  '/{-$locale}/_storefront/terms-of-service': typeof Char123LocaleChar125StorefrontTermsOfServiceRoute
  '/{-$locale}/account/addresses': typeof Char123LocaleChar125AccountAddressesRoute
  '/{-$locale}/account/overview': typeof Char123LocaleChar125AccountOverviewRoute
  '/{-$locale}/account/payment': typeof Char123LocaleChar125AccountPaymentRoute
  '/{-$locale}/account/profile': typeof Char123LocaleChar125AccountProfileRoute
  '/{-$locale}/account/sessions': typeof Char123LocaleChar125AccountSessionsRoute
  '/{-$locale}/account/wishlist': typeof Char123LocaleChar125AccountWishlistRoute
  '/{-$locale}/admin/audit': typeof Char123LocaleChar125AdminAuditRoute
  '/{-$locale}/admin/catalog': typeof Char123LocaleChar125AdminCatalogRouteWithChildren
  '/{-$locale}/admin/content': typeof Char123LocaleChar125AdminContentRoute
  '/{-$locale}/admin/coupons': typeof Char123LocaleChar125AdminCouponsRoute
  '/{-$locale}/admin/marketing': typeof Char123LocaleChar125AdminMarketingRoute
  '/{-$locale}/admin/overview': typeof Char123LocaleChar125AdminOverviewRoute
  '/{-$locale}/admin/settings': typeof Char123LocaleChar125AdminSettingsRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/auth/sign-in': typeof Char123LocaleChar125AuthSignInRoute
  '/{-$locale}/auth/sign-up': typeof Char123LocaleChar125AuthSignUpRoute
  '/{-$locale}/dev/datagrid': typeof Char123LocaleChar125DevDatagridRoute
  '/{-$locale}/_storefront/': typeof Char123LocaleChar125StorefrontIndexRoute
  '/{-$locale}/account/': typeof Char123LocaleChar125AccountIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/checkout/': typeof Char123LocaleChar125CheckoutIndexRoute
  '/{-$locale}/_storefront/categories/$handle': typeof Char123LocaleChar125StorefrontCategoriesHandleRoute
  '/{-$locale}/_storefront/collections/$handle': typeof Char123LocaleChar125StorefrontCollectionsHandleRoute
  '/{-$locale}/_storefront/products/$handle': typeof Char123LocaleChar125StorefrontProductsHandleRoute
  '/{-$locale}/account/orders/$id': typeof Char123LocaleChar125AccountOrdersIdRoute
  '/{-$locale}/admin/catalog/collections': typeof Char123LocaleChar125AdminCatalogCollectionsRouteWithChildren
  '/{-$locale}/admin/customers/$id': typeof Char123LocaleChar125AdminCustomersIdRoute
  '/{-$locale}/admin/orders/$orderId': typeof Char123LocaleChar125AdminOrdersOrderIdRoute
  '/{-$locale}/_storefront/categories/': typeof Char123LocaleChar125StorefrontCategoriesIndexRoute
  '/{-$locale}/_storefront/collections/': typeof Char123LocaleChar125StorefrontCollectionsIndexRoute
  '/{-$locale}/_storefront/products/': typeof Char123LocaleChar125StorefrontProductsIndexRoute
  '/{-$locale}/account/orders/': typeof Char123LocaleChar125AccountOrdersIndexRoute
  '/{-$locale}/admin/catalog/': typeof Char123LocaleChar125AdminCatalogIndexRoute
  '/{-$locale}/admin/customers/': typeof Char123LocaleChar125AdminCustomersIndexRoute
  '/{-$locale}/admin/orders/': typeof Char123LocaleChar125AdminOrdersIndexRoute
  '/{-$locale}/admin/catalog/categories/$handle': typeof Char123LocaleChar125AdminCatalogCategoriesHandleRoute
  '/{-$locale}/admin/catalog/collections/$handle': typeof Char123LocaleChar125AdminCatalogCollectionsHandleRoute
  '/{-$locale}/admin/catalog/products/$handle': typeof Char123LocaleChar125AdminCatalogProductsHandleRoute
  '/{-$locale}/admin/catalog/categories/': typeof Char123LocaleChar125AdminCatalogCategoriesIndexRoute
  '/{-$locale}/admin/catalog/collections/': typeof Char123LocaleChar125AdminCatalogCollectionsIndexRoute
  '/{-$locale}/admin/catalog/products/': typeof Char123LocaleChar125AdminCatalogProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/dev/emails'
    | '/{-$locale}/account'
    | '/{-$locale}/admin'
    | '/{-$locale}/auth'
    | '/{-$locale}/checkout'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/about'
    | '/{-$locale}/cart'
    | '/{-$locale}/exchanges-and-returns'
    | '/{-$locale}/faq'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/account/addresses'
    | '/{-$locale}/account/overview'
    | '/{-$locale}/account/payment'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/sessions'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/admin/audit'
    | '/{-$locale}/admin/catalog'
    | '/{-$locale}/admin/content'
    | '/{-$locale}/admin/coupons'
    | '/{-$locale}/admin/marketing'
    | '/{-$locale}/admin/overview'
    | '/{-$locale}/admin/settings'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/dev/datagrid'
    | '/{-$locale}/'
    | '/{-$locale}/account/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/checkout/'
    | '/{-$locale}/categories/$handle'
    | '/{-$locale}/collections/$handle'
    | '/{-$locale}/products/$handle'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/admin/catalog/collections'
    | '/{-$locale}/admin/customers/$id'
    | '/{-$locale}/admin/orders/$orderId'
    | '/{-$locale}/categories/'
    | '/{-$locale}/collections/'
    | '/{-$locale}/products/'
    | '/{-$locale}/account/orders/'
    | '/{-$locale}/admin/catalog/'
    | '/{-$locale}/admin/customers/'
    | '/{-$locale}/admin/orders/'
    | '/{-$locale}/admin/catalog/categories/$handle'
    | '/{-$locale}/admin/catalog/collections/$handle'
    | '/{-$locale}/admin/catalog/products/$handle'
    | '/{-$locale}/admin/catalog/categories/'
    | '/{-$locale}/admin/catalog/collections/'
    | '/{-$locale}/admin/catalog/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/dev/emails'
    | '/{-$locale}/auth'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/about'
    | '/{-$locale}/cart'
    | '/{-$locale}/exchanges-and-returns'
    | '/{-$locale}/faq'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/account/addresses'
    | '/{-$locale}/account/overview'
    | '/{-$locale}/account/payment'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/sessions'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/admin/audit'
    | '/{-$locale}/admin/content'
    | '/{-$locale}/admin/coupons'
    | '/{-$locale}/admin/marketing'
    | '/{-$locale}/admin/overview'
    | '/{-$locale}/admin/settings'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/dev/datagrid'
    | '/{-$locale}/account'
    | '/{-$locale}/admin'
    | '/{-$locale}/checkout'
    | '/{-$locale}/categories/$handle'
    | '/{-$locale}/collections/$handle'
    | '/{-$locale}/products/$handle'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/admin/customers/$id'
    | '/{-$locale}/admin/orders/$orderId'
    | '/{-$locale}/categories'
    | '/{-$locale}/collections'
    | '/{-$locale}/products'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/admin/catalog'
    | '/{-$locale}/admin/customers'
    | '/{-$locale}/admin/orders'
    | '/{-$locale}/admin/catalog/categories/$handle'
    | '/{-$locale}/admin/catalog/collections/$handle'
    | '/{-$locale}/admin/catalog/products/$handle'
    | '/{-$locale}/admin/catalog/categories'
    | '/{-$locale}/admin/catalog/collections'
    | '/{-$locale}/admin/catalog/products'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/dev/emails'
    | '/{-$locale}/_storefront'
    | '/{-$locale}/account'
    | '/{-$locale}/admin'
    | '/{-$locale}/auth'
    | '/{-$locale}/checkout'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/_storefront/about'
    | '/{-$locale}/_storefront/cart'
    | '/{-$locale}/_storefront/exchanges-and-returns'
    | '/{-$locale}/_storefront/faq'
    | '/{-$locale}/_storefront/privacy-policy'
    | '/{-$locale}/_storefront/terms-of-service'
    | '/{-$locale}/account/addresses'
    | '/{-$locale}/account/overview'
    | '/{-$locale}/account/payment'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/sessions'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/admin/audit'
    | '/{-$locale}/admin/catalog'
    | '/{-$locale}/admin/content'
    | '/{-$locale}/admin/coupons'
    | '/{-$locale}/admin/marketing'
    | '/{-$locale}/admin/overview'
    | '/{-$locale}/admin/settings'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/auth/sign-in'
    | '/{-$locale}/auth/sign-up'
    | '/{-$locale}/dev/datagrid'
    | '/{-$locale}/_storefront/'
    | '/{-$locale}/account/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/checkout/'
    | '/{-$locale}/_storefront/categories/$handle'
    | '/{-$locale}/_storefront/collections/$handle'
    | '/{-$locale}/_storefront/products/$handle'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/admin/catalog/collections'
    | '/{-$locale}/admin/customers/$id'
    | '/{-$locale}/admin/orders/$orderId'
    | '/{-$locale}/_storefront/categories/'
    | '/{-$locale}/_storefront/collections/'
    | '/{-$locale}/_storefront/products/'
    | '/{-$locale}/account/orders/'
    | '/{-$locale}/admin/catalog/'
    | '/{-$locale}/admin/customers/'
    | '/{-$locale}/admin/orders/'
    | '/{-$locale}/admin/catalog/categories/$handle'
    | '/{-$locale}/admin/catalog/collections/$handle'
    | '/{-$locale}/admin/catalog/products/$handle'
    | '/{-$locale}/admin/catalog/categories/'
    | '/{-$locale}/admin/catalog/collections/'
    | '/{-$locale}/admin/catalog/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  DevEmailsRoute: typeof DevEmailsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/checkout': {
      id: '/{-$locale}/checkout'
      path: '/checkout'
      fullPath: '/{-$locale}/checkout'
      preLoaderRoute: typeof Char123LocaleChar125CheckoutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/account': {
      id: '/{-$locale}/account'
      path: '/account'
      fullPath: '/{-$locale}/account'
      preLoaderRoute: typeof Char123LocaleChar125AccountRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/_storefront': {
      id: '/{-$locale}/_storefront'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/dev/emails': {
      id: '/dev/emails'
      path: '/dev/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof DevEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/checkout/': {
      id: '/{-$locale}/checkout/'
      path: '/'
      fullPath: '/{-$locale}/checkout/'
      preLoaderRoute: typeof Char123LocaleChar125CheckoutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125CheckoutRoute
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/account/': {
      id: '/{-$locale}/account/'
      path: '/'
      fullPath: '/{-$locale}/account/'
      preLoaderRoute: typeof Char123LocaleChar125AccountIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/_storefront/': {
      id: '/{-$locale}/_storefront/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontIndexRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/dev/datagrid': {
      id: '/{-$locale}/dev/datagrid'
      path: '/dev/datagrid'
      fullPath: '/{-$locale}/dev/datagrid'
      preLoaderRoute: typeof Char123LocaleChar125DevDatagridRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth/sign-up': {
      id: '/{-$locale}/auth/sign-up'
      path: '/sign-up'
      fullPath: '/{-$locale}/auth/sign-up'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignUpRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/sign-in': {
      id: '/{-$locale}/auth/sign-in'
      path: '/sign-in'
      fullPath: '/{-$locale}/auth/sign-in'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignInRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/reset-password': {
      id: '/{-$locale}/auth/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/auth/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/auth/forgot-password': {
      id: '/{-$locale}/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/auth/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/{-$locale}/admin/settings': {
      id: '/{-$locale}/admin/settings'
      path: '/settings'
      fullPath: '/{-$locale}/admin/settings'
      preLoaderRoute: typeof Char123LocaleChar125AdminSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/overview': {
      id: '/{-$locale}/admin/overview'
      path: '/overview'
      fullPath: '/{-$locale}/admin/overview'
      preLoaderRoute: typeof Char123LocaleChar125AdminOverviewRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/marketing': {
      id: '/{-$locale}/admin/marketing'
      path: '/marketing'
      fullPath: '/{-$locale}/admin/marketing'
      preLoaderRoute: typeof Char123LocaleChar125AdminMarketingRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/coupons': {
      id: '/{-$locale}/admin/coupons'
      path: '/coupons'
      fullPath: '/{-$locale}/admin/coupons'
      preLoaderRoute: typeof Char123LocaleChar125AdminCouponsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/content': {
      id: '/{-$locale}/admin/content'
      path: '/content'
      fullPath: '/{-$locale}/admin/content'
      preLoaderRoute: typeof Char123LocaleChar125AdminContentRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/catalog': {
      id: '/{-$locale}/admin/catalog'
      path: '/catalog'
      fullPath: '/{-$locale}/admin/catalog'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/audit': {
      id: '/{-$locale}/admin/audit'
      path: '/audit'
      fullPath: '/{-$locale}/admin/audit'
      preLoaderRoute: typeof Char123LocaleChar125AdminAuditRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/account/wishlist': {
      id: '/{-$locale}/account/wishlist'
      path: '/wishlist'
      fullPath: '/{-$locale}/account/wishlist'
      preLoaderRoute: typeof Char123LocaleChar125AccountWishlistRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/account/sessions': {
      id: '/{-$locale}/account/sessions'
      path: '/sessions'
      fullPath: '/{-$locale}/account/sessions'
      preLoaderRoute: typeof Char123LocaleChar125AccountSessionsRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/account/profile': {
      id: '/{-$locale}/account/profile'
      path: '/profile'
      fullPath: '/{-$locale}/account/profile'
      preLoaderRoute: typeof Char123LocaleChar125AccountProfileRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/account/payment': {
      id: '/{-$locale}/account/payment'
      path: '/payment'
      fullPath: '/{-$locale}/account/payment'
      preLoaderRoute: typeof Char123LocaleChar125AccountPaymentRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/account/overview': {
      id: '/{-$locale}/account/overview'
      path: '/overview'
      fullPath: '/{-$locale}/account/overview'
      preLoaderRoute: typeof Char123LocaleChar125AccountOverviewRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/account/addresses': {
      id: '/{-$locale}/account/addresses'
      path: '/addresses'
      fullPath: '/{-$locale}/account/addresses'
      preLoaderRoute: typeof Char123LocaleChar125AccountAddressesRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/_storefront/terms-of-service': {
      id: '/{-$locale}/_storefront/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontTermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/privacy-policy': {
      id: '/{-$locale}/_storefront/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontPrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/faq': {
      id: '/{-$locale}/_storefront/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontFaqRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/exchanges-and-returns': {
      id: '/{-$locale}/_storefront/exchanges-and-returns'
      path: '/exchanges-and-returns'
      fullPath: '/{-$locale}/exchanges-and-returns'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontExchangesAndReturnsRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/cart': {
      id: '/{-$locale}/_storefront/cart'
      path: '/cart'
      fullPath: '/{-$locale}/cart'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontCartRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/about': {
      id: '/{-$locale}/_storefront/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontAboutRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin/orders/': {
      id: '/{-$locale}/admin/orders/'
      path: '/orders'
      fullPath: '/{-$locale}/admin/orders/'
      preLoaderRoute: typeof Char123LocaleChar125AdminOrdersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/customers/': {
      id: '/{-$locale}/admin/customers/'
      path: '/customers'
      fullPath: '/{-$locale}/admin/customers/'
      preLoaderRoute: typeof Char123LocaleChar125AdminCustomersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/catalog/': {
      id: '/{-$locale}/admin/catalog/'
      path: '/'
      fullPath: '/{-$locale}/admin/catalog/'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
    '/{-$locale}/account/orders/': {
      id: '/{-$locale}/account/orders/'
      path: '/orders'
      fullPath: '/{-$locale}/account/orders/'
      preLoaderRoute: typeof Char123LocaleChar125AccountOrdersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/_storefront/products/': {
      id: '/{-$locale}/_storefront/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/collections/': {
      id: '/{-$locale}/_storefront/collections/'
      path: '/collections'
      fullPath: '/{-$locale}/collections/'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontCollectionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/categories/': {
      id: '/{-$locale}/_storefront/categories/'
      path: '/categories'
      fullPath: '/{-$locale}/categories/'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontCategoriesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/admin/orders/$orderId': {
      id: '/{-$locale}/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/{-$locale}/admin/orders/$orderId'
      preLoaderRoute: typeof Char123LocaleChar125AdminOrdersOrderIdRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/customers/$id': {
      id: '/{-$locale}/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/{-$locale}/admin/customers/$id'
      preLoaderRoute: typeof Char123LocaleChar125AdminCustomersIdRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/catalog/collections': {
      id: '/{-$locale}/admin/catalog/collections'
      path: '/collections'
      fullPath: '/{-$locale}/admin/catalog/collections'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogCollectionsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
    '/{-$locale}/account/orders/$id': {
      id: '/{-$locale}/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/{-$locale}/account/orders/$id'
      preLoaderRoute: typeof Char123LocaleChar125AccountOrdersIdRouteImport
      parentRoute: typeof Char123LocaleChar125AccountRoute
    }
    '/{-$locale}/_storefront/products/$handle': {
      id: '/{-$locale}/_storefront/products/$handle'
      path: '/products/$handle'
      fullPath: '/{-$locale}/products/$handle'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontProductsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/collections/$handle': {
      id: '/{-$locale}/_storefront/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/{-$locale}/collections/$handle'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontCollectionsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/_storefront/categories/$handle': {
      id: '/{-$locale}/_storefront/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/{-$locale}/categories/$handle'
      preLoaderRoute: typeof Char123LocaleChar125StorefrontCategoriesHandleRouteImport
      parentRoute: typeof Char123LocaleChar125StorefrontRoute
    }
    '/{-$locale}/admin/catalog/products/': {
      id: '/{-$locale}/admin/catalog/products/'
      path: '/products'
      fullPath: '/{-$locale}/admin/catalog/products/'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
    '/{-$locale}/admin/catalog/collections/': {
      id: '/{-$locale}/admin/catalog/collections/'
      path: '/'
      fullPath: '/{-$locale}/admin/catalog/collections/'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogCollectionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogCollectionsRoute
    }
    '/{-$locale}/admin/catalog/categories/': {
      id: '/{-$locale}/admin/catalog/categories/'
      path: '/categories'
      fullPath: '/{-$locale}/admin/catalog/categories/'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogCategoriesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
    '/{-$locale}/admin/catalog/products/$handle': {
      id: '/{-$locale}/admin/catalog/products/$handle'
      path: '/products/$handle'
      fullPath: '/{-$locale}/admin/catalog/products/$handle'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogProductsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
    '/{-$locale}/admin/catalog/collections/$handle': {
      id: '/{-$locale}/admin/catalog/collections/$handle'
      path: '/$handle'
      fullPath: '/{-$locale}/admin/catalog/collections/$handle'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogCollectionsHandleRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogCollectionsRoute
    }
    '/{-$locale}/admin/catalog/categories/$handle': {
      id: '/{-$locale}/admin/catalog/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/{-$locale}/admin/catalog/categories/$handle'
      preLoaderRoute: typeof Char123LocaleChar125AdminCatalogCategoriesHandleRouteImport
      parentRoute: typeof Char123LocaleChar125AdminCatalogRoute
    }
  }
}

interface Char123LocaleChar125StorefrontRouteChildren {
  Char123LocaleChar125StorefrontAboutRoute: typeof Char123LocaleChar125StorefrontAboutRoute
  Char123LocaleChar125StorefrontCartRoute: typeof Char123LocaleChar125StorefrontCartRoute
  Char123LocaleChar125StorefrontExchangesAndReturnsRoute: typeof Char123LocaleChar125StorefrontExchangesAndReturnsRoute
  Char123LocaleChar125StorefrontFaqRoute: typeof Char123LocaleChar125StorefrontFaqRoute
  Char123LocaleChar125StorefrontPrivacyPolicyRoute: typeof Char123LocaleChar125StorefrontPrivacyPolicyRoute
  Char123LocaleChar125StorefrontTermsOfServiceRoute: typeof Char123LocaleChar125StorefrontTermsOfServiceRoute
  Char123LocaleChar125StorefrontIndexRoute: typeof Char123LocaleChar125StorefrontIndexRoute
  Char123LocaleChar125StorefrontCategoriesHandleRoute: typeof Char123LocaleChar125StorefrontCategoriesHandleRoute
  Char123LocaleChar125StorefrontCollectionsHandleRoute: typeof Char123LocaleChar125StorefrontCollectionsHandleRoute
  Char123LocaleChar125StorefrontProductsHandleRoute: typeof Char123LocaleChar125StorefrontProductsHandleRoute
  Char123LocaleChar125StorefrontCategoriesIndexRoute: typeof Char123LocaleChar125StorefrontCategoriesIndexRoute
  Char123LocaleChar125StorefrontCollectionsIndexRoute: typeof Char123LocaleChar125StorefrontCollectionsIndexRoute
  Char123LocaleChar125StorefrontProductsIndexRoute: typeof Char123LocaleChar125StorefrontProductsIndexRoute
}

const Char123LocaleChar125StorefrontRouteChildren: Char123LocaleChar125StorefrontRouteChildren =
  {
    Char123LocaleChar125StorefrontAboutRoute:
      Char123LocaleChar125StorefrontAboutRoute,
    Char123LocaleChar125StorefrontCartRoute:
      Char123LocaleChar125StorefrontCartRoute,
    Char123LocaleChar125StorefrontExchangesAndReturnsRoute:
      Char123LocaleChar125StorefrontExchangesAndReturnsRoute,
    Char123LocaleChar125StorefrontFaqRoute:
      Char123LocaleChar125StorefrontFaqRoute,
    Char123LocaleChar125StorefrontPrivacyPolicyRoute:
      Char123LocaleChar125StorefrontPrivacyPolicyRoute,
    Char123LocaleChar125StorefrontTermsOfServiceRoute:
      Char123LocaleChar125StorefrontTermsOfServiceRoute,
    Char123LocaleChar125StorefrontIndexRoute:
      Char123LocaleChar125StorefrontIndexRoute,
    Char123LocaleChar125StorefrontCategoriesHandleRoute:
      Char123LocaleChar125StorefrontCategoriesHandleRoute,
    Char123LocaleChar125StorefrontCollectionsHandleRoute:
      Char123LocaleChar125StorefrontCollectionsHandleRoute,
    Char123LocaleChar125StorefrontProductsHandleRoute:
      Char123LocaleChar125StorefrontProductsHandleRoute,
    Char123LocaleChar125StorefrontCategoriesIndexRoute:
      Char123LocaleChar125StorefrontCategoriesIndexRoute,
    Char123LocaleChar125StorefrontCollectionsIndexRoute:
      Char123LocaleChar125StorefrontCollectionsIndexRoute,
    Char123LocaleChar125StorefrontProductsIndexRoute:
      Char123LocaleChar125StorefrontProductsIndexRoute,
  }

const Char123LocaleChar125StorefrontRouteWithChildren =
  Char123LocaleChar125StorefrontRoute._addFileChildren(
    Char123LocaleChar125StorefrontRouteChildren,
  )

interface Char123LocaleChar125AccountRouteChildren {
  Char123LocaleChar125AccountAddressesRoute: typeof Char123LocaleChar125AccountAddressesRoute
  Char123LocaleChar125AccountOverviewRoute: typeof Char123LocaleChar125AccountOverviewRoute
  Char123LocaleChar125AccountPaymentRoute: typeof Char123LocaleChar125AccountPaymentRoute
  Char123LocaleChar125AccountProfileRoute: typeof Char123LocaleChar125AccountProfileRoute
  Char123LocaleChar125AccountSessionsRoute: typeof Char123LocaleChar125AccountSessionsRoute
  Char123LocaleChar125AccountWishlistRoute: typeof Char123LocaleChar125AccountWishlistRoute
  Char123LocaleChar125AccountIndexRoute: typeof Char123LocaleChar125AccountIndexRoute
  Char123LocaleChar125AccountOrdersIdRoute: typeof Char123LocaleChar125AccountOrdersIdRoute
  Char123LocaleChar125AccountOrdersIndexRoute: typeof Char123LocaleChar125AccountOrdersIndexRoute
}

const Char123LocaleChar125AccountRouteChildren: Char123LocaleChar125AccountRouteChildren =
  {
    Char123LocaleChar125AccountAddressesRoute:
      Char123LocaleChar125AccountAddressesRoute,
    Char123LocaleChar125AccountOverviewRoute:
      Char123LocaleChar125AccountOverviewRoute,
    Char123LocaleChar125AccountPaymentRoute:
      Char123LocaleChar125AccountPaymentRoute,
    Char123LocaleChar125AccountProfileRoute:
      Char123LocaleChar125AccountProfileRoute,
    Char123LocaleChar125AccountSessionsRoute:
      Char123LocaleChar125AccountSessionsRoute,
    Char123LocaleChar125AccountWishlistRoute:
      Char123LocaleChar125AccountWishlistRoute,
    Char123LocaleChar125AccountIndexRoute:
      Char123LocaleChar125AccountIndexRoute,
    Char123LocaleChar125AccountOrdersIdRoute:
      Char123LocaleChar125AccountOrdersIdRoute,
    Char123LocaleChar125AccountOrdersIndexRoute:
      Char123LocaleChar125AccountOrdersIndexRoute,
  }

const Char123LocaleChar125AccountRouteWithChildren =
  Char123LocaleChar125AccountRoute._addFileChildren(
    Char123LocaleChar125AccountRouteChildren,
  )

interface Char123LocaleChar125AdminCatalogCollectionsRouteChildren {
  Char123LocaleChar125AdminCatalogCollectionsHandleRoute: typeof Char123LocaleChar125AdminCatalogCollectionsHandleRoute
  Char123LocaleChar125AdminCatalogCollectionsIndexRoute: typeof Char123LocaleChar125AdminCatalogCollectionsIndexRoute
}

const Char123LocaleChar125AdminCatalogCollectionsRouteChildren: Char123LocaleChar125AdminCatalogCollectionsRouteChildren =
  {
    Char123LocaleChar125AdminCatalogCollectionsHandleRoute:
      Char123LocaleChar125AdminCatalogCollectionsHandleRoute,
    Char123LocaleChar125AdminCatalogCollectionsIndexRoute:
      Char123LocaleChar125AdminCatalogCollectionsIndexRoute,
  }

const Char123LocaleChar125AdminCatalogCollectionsRouteWithChildren =
  Char123LocaleChar125AdminCatalogCollectionsRoute._addFileChildren(
    Char123LocaleChar125AdminCatalogCollectionsRouteChildren,
  )

interface Char123LocaleChar125AdminCatalogRouteChildren {
  Char123LocaleChar125AdminCatalogCollectionsRoute: typeof Char123LocaleChar125AdminCatalogCollectionsRouteWithChildren
  Char123LocaleChar125AdminCatalogIndexRoute: typeof Char123LocaleChar125AdminCatalogIndexRoute
  Char123LocaleChar125AdminCatalogCategoriesHandleRoute: typeof Char123LocaleChar125AdminCatalogCategoriesHandleRoute
  Char123LocaleChar125AdminCatalogProductsHandleRoute: typeof Char123LocaleChar125AdminCatalogProductsHandleRoute
  Char123LocaleChar125AdminCatalogCategoriesIndexRoute: typeof Char123LocaleChar125AdminCatalogCategoriesIndexRoute
  Char123LocaleChar125AdminCatalogProductsIndexRoute: typeof Char123LocaleChar125AdminCatalogProductsIndexRoute
}

const Char123LocaleChar125AdminCatalogRouteChildren: Char123LocaleChar125AdminCatalogRouteChildren =
  {
    Char123LocaleChar125AdminCatalogCollectionsRoute:
      Char123LocaleChar125AdminCatalogCollectionsRouteWithChildren,
    Char123LocaleChar125AdminCatalogIndexRoute:
      Char123LocaleChar125AdminCatalogIndexRoute,
    Char123LocaleChar125AdminCatalogCategoriesHandleRoute:
      Char123LocaleChar125AdminCatalogCategoriesHandleRoute,
    Char123LocaleChar125AdminCatalogProductsHandleRoute:
      Char123LocaleChar125AdminCatalogProductsHandleRoute,
    Char123LocaleChar125AdminCatalogCategoriesIndexRoute:
      Char123LocaleChar125AdminCatalogCategoriesIndexRoute,
    Char123LocaleChar125AdminCatalogProductsIndexRoute:
      Char123LocaleChar125AdminCatalogProductsIndexRoute,
  }

const Char123LocaleChar125AdminCatalogRouteWithChildren =
  Char123LocaleChar125AdminCatalogRoute._addFileChildren(
    Char123LocaleChar125AdminCatalogRouteChildren,
  )

interface Char123LocaleChar125AdminRouteChildren {
  Char123LocaleChar125AdminAuditRoute: typeof Char123LocaleChar125AdminAuditRoute
  Char123LocaleChar125AdminCatalogRoute: typeof Char123LocaleChar125AdminCatalogRouteWithChildren
  Char123LocaleChar125AdminContentRoute: typeof Char123LocaleChar125AdminContentRoute
  Char123LocaleChar125AdminCouponsRoute: typeof Char123LocaleChar125AdminCouponsRoute
  Char123LocaleChar125AdminMarketingRoute: typeof Char123LocaleChar125AdminMarketingRoute
  Char123LocaleChar125AdminOverviewRoute: typeof Char123LocaleChar125AdminOverviewRoute
  Char123LocaleChar125AdminSettingsRoute: typeof Char123LocaleChar125AdminSettingsRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
  Char123LocaleChar125AdminCustomersIdRoute: typeof Char123LocaleChar125AdminCustomersIdRoute
  Char123LocaleChar125AdminOrdersOrderIdRoute: typeof Char123LocaleChar125AdminOrdersOrderIdRoute
  Char123LocaleChar125AdminCustomersIndexRoute: typeof Char123LocaleChar125AdminCustomersIndexRoute
  Char123LocaleChar125AdminOrdersIndexRoute: typeof Char123LocaleChar125AdminOrdersIndexRoute
}

const Char123LocaleChar125AdminRouteChildren: Char123LocaleChar125AdminRouteChildren =
  {
    Char123LocaleChar125AdminAuditRoute: Char123LocaleChar125AdminAuditRoute,
    Char123LocaleChar125AdminCatalogRoute:
      Char123LocaleChar125AdminCatalogRouteWithChildren,
    Char123LocaleChar125AdminContentRoute:
      Char123LocaleChar125AdminContentRoute,
    Char123LocaleChar125AdminCouponsRoute:
      Char123LocaleChar125AdminCouponsRoute,
    Char123LocaleChar125AdminMarketingRoute:
      Char123LocaleChar125AdminMarketingRoute,
    Char123LocaleChar125AdminOverviewRoute:
      Char123LocaleChar125AdminOverviewRoute,
    Char123LocaleChar125AdminSettingsRoute:
      Char123LocaleChar125AdminSettingsRoute,
    Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
    Char123LocaleChar125AdminCustomersIdRoute:
      Char123LocaleChar125AdminCustomersIdRoute,
    Char123LocaleChar125AdminOrdersOrderIdRoute:
      Char123LocaleChar125AdminOrdersOrderIdRoute,
    Char123LocaleChar125AdminCustomersIndexRoute:
      Char123LocaleChar125AdminCustomersIndexRoute,
    Char123LocaleChar125AdminOrdersIndexRoute:
      Char123LocaleChar125AdminOrdersIndexRoute,
  }

const Char123LocaleChar125AdminRouteWithChildren =
  Char123LocaleChar125AdminRoute._addFileChildren(
    Char123LocaleChar125AdminRouteChildren,
  )

interface Char123LocaleChar125AuthRouteChildren {
  Char123LocaleChar125AuthForgotPasswordRoute: typeof Char123LocaleChar125AuthForgotPasswordRoute
  Char123LocaleChar125AuthResetPasswordRoute: typeof Char123LocaleChar125AuthResetPasswordRoute
  Char123LocaleChar125AuthSignInRoute: typeof Char123LocaleChar125AuthSignInRoute
  Char123LocaleChar125AuthSignUpRoute: typeof Char123LocaleChar125AuthSignUpRoute
}

const Char123LocaleChar125AuthRouteChildren: Char123LocaleChar125AuthRouteChildren =
  {
    Char123LocaleChar125AuthForgotPasswordRoute:
      Char123LocaleChar125AuthForgotPasswordRoute,
    Char123LocaleChar125AuthResetPasswordRoute:
      Char123LocaleChar125AuthResetPasswordRoute,
    Char123LocaleChar125AuthSignInRoute: Char123LocaleChar125AuthSignInRoute,
    Char123LocaleChar125AuthSignUpRoute: Char123LocaleChar125AuthSignUpRoute,
  }

const Char123LocaleChar125AuthRouteWithChildren =
  Char123LocaleChar125AuthRoute._addFileChildren(
    Char123LocaleChar125AuthRouteChildren,
  )

interface Char123LocaleChar125CheckoutRouteChildren {
  Char123LocaleChar125CheckoutIndexRoute: typeof Char123LocaleChar125CheckoutIndexRoute
}

const Char123LocaleChar125CheckoutRouteChildren: Char123LocaleChar125CheckoutRouteChildren =
  {
    Char123LocaleChar125CheckoutIndexRoute:
      Char123LocaleChar125CheckoutIndexRoute,
  }

const Char123LocaleChar125CheckoutRouteWithChildren =
  Char123LocaleChar125CheckoutRoute._addFileChildren(
    Char123LocaleChar125CheckoutRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125StorefrontRoute: typeof Char123LocaleChar125StorefrontRouteWithChildren
  Char123LocaleChar125AccountRoute: typeof Char123LocaleChar125AccountRouteWithChildren
  Char123LocaleChar125AdminRoute: typeof Char123LocaleChar125AdminRouteWithChildren
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRouteWithChildren
  Char123LocaleChar125CheckoutRoute: typeof Char123LocaleChar125CheckoutRouteWithChildren
  Char123LocaleChar125DevDatagridRoute: typeof Char123LocaleChar125DevDatagridRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125StorefrontRoute:
    Char123LocaleChar125StorefrontRouteWithChildren,
  Char123LocaleChar125AccountRoute:
    Char123LocaleChar125AccountRouteWithChildren,
  Char123LocaleChar125AdminRoute: Char123LocaleChar125AdminRouteWithChildren,
  Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRouteWithChildren,
  Char123LocaleChar125CheckoutRoute:
    Char123LocaleChar125CheckoutRouteWithChildren,
  Char123LocaleChar125DevDatagridRoute: Char123LocaleChar125DevDatagridRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  DevEmailsRoute: DevEmailsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
